package com.spamstopper.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme
val md_theme_light_primary = Color(0xFF1976D2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBDEFB)
val md_theme_light_onPrimaryContainer = Color(0xFF0D47A1)
val md_theme_light_secondary = Color(0xFF4CAF50)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC8E6C9)
val md_theme_light_onSecondaryContainer = Color(0xFF1B5E20)
val md_theme_light_error = Color(0xFFF44336)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFCDD2)
val md_theme_light_onErrorContainer = Color(0xFFB71C1C)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF212121)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF212121)
val md_theme_light_surfaceVariant = Color(0xFFE0E0E0)
val md_theme_light_onSurfaceVariant = Color(0xFF424242)
val md_theme_light_outline = Color(0xFF757575)

// Dark Theme
val md_theme_dark_primary = Color(0xFF64B5F6)
val md_theme_dark_onPrimary = Color(0xFF0D47A1)
val md_theme_dark_primaryContainer = Color(0xFF1565C0)
val md_theme_dark_onPrimaryContainer = Color(0xFFE3F2FD)
val md_theme_dark_secondary = Color(0xFF81C784)
val md_theme_dark_onSecondary = Color(0xFF1B5E20)
val md_theme_dark_secondaryContainer = Color(0xFF388E3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8F5E9)
val md_theme_dark_error = Color(0xFFEF5350)
val md_theme_dark_onError = Color(0xFFB71C1C)
val md_theme_dark_errorContainer = Color(0xFFC62828)
val md_theme_dark_onErrorContainer = Color(0xFFFFEBEE)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE0E0E0)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFE0E0E0)
val md_theme_dark_surfaceVariant = Color(0xFF424242)
val md_theme_dark_onSurfaceVariant = Color(0xFFBDBDBD)
val md_theme_dark_outline = Color(0xFF757575)